# Generated by Django 2.2.6 on 2019-10-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0004_auto_20191029_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='nba_record',
            name='in_losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nba_record',
            name='in_pushes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nba_record',
            name='in_wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
