# Generated by Django 2.2.6 on 2019-11-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='in_play',
            field=models.FloatField(default=0),
        ),
    ]
