# Generated by Django 2.2.6 on 2019-11-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_in_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='in_play',
            field=models.FloatField(default=0, null=True),
        ),
    ]
