# Generated by Django 2.2.6 on 2019-10-28 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=30)),
                ('away_team', models.CharField(max_length=30)),
                ('home_spread', models.FloatField(null=True)),
                ('away_spread', models.FloatField(null=True)),
                ('date_time', models.DateTimeField()),
                ('neutral', models.BooleanField()),
                ('home_score', models.FloatField(null=True)),
                ('away_score', models.FloatField(null=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.Week')),
            ],
        ),
    ]
