# Generated by Django 2.2.6 on 2019-10-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='neutral',
        ),
    ]
