# Generated by Django 2.2.6 on 2019-10-28 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nfl', '0002_remove_game_neutral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['pk']},
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.CharField(max_length=40)),
                ('outcome', models.CharField(choices=[('win', 'win'), ('loss', 'loss'), ('push', 'push')], max_length=5, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfl_pick_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
