# Generated by Django 2.2.6 on 2019-10-29 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nfl', '0003_auto_20191028_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nfl_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('pushes', models.PositiveIntegerField(default=0)),
                ('in_wins', models.PositiveIntegerField(default=0)),
                ('in_losses', models.PositiveIntegerField(default=0)),
                ('in_pushes', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
