# Generated by Django 2.2.6 on 2019-11-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0004_nfl_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='wager',
            field=models.FloatField(null=True),
        ),
    ]
