# Generated by Django 2.2.6 on 2019-10-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=30)),
                ('away_team', models.CharField(max_length=30)),
                ('home_spread', models.FloatField(null=True)),
                ('away_spread', models.FloatField(null=True)),
                ('date_time', models.DateTimeField()),
                ('neutral', models.BooleanField()),
                ('home_score', models.FloatField(null=True)),
                ('away_score', models.FloatField(null=True)),
            ],
        ),
    ]
